language: ruby
rvm:
- 2.1.3
deploy:
  provider: heroku
  api_key:
    secure: LMoYvx15F/djuti+6QxcO4WGOHXxYMIOepDYyPvF3eim7aGWgkbq4W2Jk095km6FZrLsidVcWP1UGcdKYe/y6GW0MR8Tt4RWXtxEl60TGeKgtEo27X9V/CnL9eUpLcpXXNNEUTrrmJFC94cQwq1cikZSL22gRjkfQMQnJ8oz1Fo=
  app: icco-mood
  on:
    repo: icco/inspiration
