language: ruby
rvm:
- 2.1.3
deploy:
  provider: heroku
  api_key:
    secure: Fh6rIeoaGD8gy9d8oeEh4Zc8mK4hPhoMZKHTTU/xjl16sAmymi1fCBsv0yy7KwLaK9za1OnPul7njyNL1xjtciH3OTJ9iwcZVHV6VcXsoETSRRiN3s2G/ue2dGys76uJ3yRkXV+ayGuc4PZnHTrr3G3+qDVP16xHkPMy3SwquLc=
  strategy: api
  app: icco-mood
  on:
    repo: icco/inspiration
bundler_args: --without development
cache: bundler
